export enum Permission {
  // Roles & Permissions Management
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',
  ASSIGN_ROLE_PERMISSIONS = 'ASSIGN_ROLE_PERMISSIONS',

  // Users Management
  VIEW_USERS = 'VIEW_USERS',
  CREATE_USERS = 'CREATE_USERS',
  EDIT_USERS = 'EDIT_USERS',

  // Employees Management
  CREATE_EMPLOYEES = 'CREATE_EMPLOYEES',
  EDIT_EMPLOYEES = 'EDIT_EMPLOYEES',
  VIEW_EMPLOYEES = 'VIEW_EMPLOYEES',

  // Patients / Clinical Records
  VIEW_PATIENTS = 'VIEW_PATIENTS',
  CREATE_PATIENTS = 'CREATE_PATIENTS',
  EDIT_PATIENTS = 'EDIT_PATIENTS',
  VIEW_PATIENT_CLINICAL_RECORDS = 'VIEW_PATIENT_CLINICAL_RECORDS',
  CREATE_PATIENT_CLINICAL_RECORDS = 'CREATE_PATIENT_CLINICAL_RECORDS',
  EDIT_PATIENT_CLINICAL_RECORDS = 'EDIT_PATIENT_CLINICAL_RECORDS',
  VIEW_CONFIDENTIAL_NOTES = 'VIEW_CONFIDENTIAL_NOTES',
  CREATE_CONFIDENTIAL_NOTES = 'CREATE_CONFIDENTIAL_NOTES',
  VIEW_SESSIONS = 'VIEW_SESSIONS',
  CREATE_SESSIONS = 'CREATE_SESSIONS',
  EDIT_SESSIONS = 'EDIT_SESSIONS',
  ASSIGN_PATIENT_TASKS = 'ASSIGN_PATIENT_TASKS',
  MANAGE_PATIENT_ALERTS = 'MANAGE_PATIENT_ALERTS',

  // Appointments
  VIEW_SCHEDULED_APPOINTMENTS = 'VIEW_SCHEDULED_APPOINTMENTS',
  CREATE_APPOINTMENTS = 'CREATE_APPOINTMENTS',
  EDIT_APPOINTMENTS = 'EDIT_APPOINTMENTS',
  CANCEL_APPOINTMENTS = 'CANCEL_APPOINTMENTS',

  // Inventory
  VIEW_INVENTORY = 'VIEW_INVENTORY',
  MANAGE_INVENTORY = 'MANAGE_INVENTORY',

  // Prescriptions / Deliveries
  CREATE_PRESCRIPTIONS = 'CREATE_PRESCRIPTIONS',
  DELIVER_MEDICATION = 'DELIVER_MEDICATION',

  // Billing & Payments
  VIEW_INVOICES = 'VIEW_INVOICES',
  GENERATE_INVOICES = 'GENERATE_INVOICES',
  REGISTER_PAYMENTS = 'REGISTER_PAYMENTS',
  VIEW_ACCOUNTS_RECEIVABLE = 'VIEW_ACCOUNTS_RECEIVABLE',

  // Payroll
  VIEW_PAYROLL = 'VIEW_PAYROLL',
  MANAGE_PAYROLL = 'MANAGE_PAYROLL',

  // Reports
  VIEW_REPORTS_FINANCIAL = 'VIEW_REPORTS_FINANCIAL',
  VIEW_REPORTS_CLINICAL = 'VIEW_REPORTS_CLINICAL',
  VIEW_REPORTS_INVENTORY = 'VIEW_REPORTS_INVENTORY',
  VIEW_REPORTS_HR = 'VIEW_REPORTS_HR',

  // Audit
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
}
